// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpupsmanbvuplemfypjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdXBzbWFuYnZ1cGxlbWZ5cGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDg0NTIsImV4cCI6MjA2MDE4NDQ1Mn0.H_zS4QoZk2Q5ICWPXFfMpTKJVs9OdLS4wdumARcUhvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);